# Generated by Django 5.1.4 on 2025-01-11 19:18

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_remove_student_image_student_created_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='addressField',
        ),
        migrations.AddField(
            model_name='student',
            name='address',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 1, 11, 19, 18, 16, 352523)),
        ),
    ]
