# Generated by Django 5.1.4 on 2025-01-12 01:48

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_remove_student_addressfield_student_address_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('speed', models.IntegerField(default=50)),
                ('model', models.CharField(max_length=200)),
                ('year', models.IntegerField()),
                ('created_at', models.DateTimeField(default=datetime.datetime(2025, 1, 12, 1, 48, 16, 73727))),
            ],
        ),
        migrations.DeleteModel(
            name='Product',
        ),
        migrations.AlterField(
            model_name='student',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 1, 12, 1, 48, 16, 73582)),
        ),
    ]
