# Generated by Django 5.1.4 on 2025-01-14 07:00

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_alter_student_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 1, 14, 7, 0, 22, 45345, tzinfo=datetime.timezone.utc)),
        ),
    ]
