# Generated by Django 5.1.4 on 2025-01-16 13:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0002_alter_receipe_receipe_image'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Receipe',
            new_name='Recipe',
        ),
        migrations.RenameField(
            model_name='recipe',
            old_name='receipe_description',
            new_name='recipe_description',
        ),
        migrations.RenameField(
            model_name='recipe',
            old_name='receipe_image',
            new_name='recipe_image',
        ),
        migrations.RenameField(
            model_name='recipe',
            old_name='receipe_name',
            new_name='recipe_name',
        ),
    ]
